const Description = document.querySelector("input#description")
console.log(Description)
const Amount = document.querySelector("input#amount")
console.log(Amount)
const Date = document.querySelector("input#date")
console.log(Date)
